# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgqtISGK53N4yTMhW_F-0D9wBOm1fcRe
"""

# @title Default title text
from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("f:/Suraksha-1/suraksha_pune_dataset_with_coords.csv")
df.head()

X = df.drop(columns=['area', 'feedback_text', 'psi_score'])
y = df['psi_score']

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=200,
    max_depth=12,
    random_state=42
)

model.fit(X_train, y_train)

from sklearn.metrics import mean_absolute_error, r2_score

preds = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, preds))
print("R² Score:", r2_score(y_test, preds))

import matplotlib.pyplot as plt

importances = model.feature_importances_
features = X.columns

plt.figure(figsize=(8,5))
plt.barh(features, importances)
plt.title("Feature Importance in PSI Prediction")
plt.show()

def adjusted_psi(ml_psi, user_rating):
    weight = user_rating / 5
    return ml_psi * weight

final_psi = (0.6 * model.predict(X_scaled)) + (0.4 * df['psi_score'])

import joblib

joblib.dump(model, "suraksha_psi_model.pkl")
joblib.dump(scaler, "scaler.pkl")

files.download("suraksha_psi_model.pkl")
files.download("scaler.pkl")